spring :
  rabbitmq :
    host : localhost
    port : 5672
    username : guest
    password : guest


rabbitmq :
  queue  :
    name : hargun_queue
  exchange :
    name : hargun_exchange
  routing:
    name : hargun_routing_key